### ISSUE TITLE
Verbose setting gets lost when embeddings and embedding model provided

### ISSUE THREAD

**Issue by ianrandman** [semandex/BERTopic#4]
### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Desribe the bug

https://github.com/MaartenGr/BERTopic/issues/2079

### BERTopic Version

0.16.2.0

**Comment by djmakwana** [comment]
This is done in https://github.com/semandex/BERTopic/pull/5 and https://github.com/MaartenGr/BERTopic/pull/2085
